---
title: "formula"
output: rmarkdown::pdf_document
vignette: >
  %\VignetteIndexEntry{formula}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(tidyverse)
```


```{r}
?formula

methods(class = "formula")

f <- formula(y ~ a + b + a:b)
class(f)
typeof(f)
sloop::otype(f)

f_ <- formula(y ~ a + b + I(a*b))

fu <- update(f, . ~ . -1)
fu

N <- 100

a <- rnorm(n = N)
b <- rnorm(n = N)

y <- 1 + 2 * a + 3 * b + 4 * a * b + rnorm(n = N)

dat <- data.frame(y = y, a = a, b = b)

model.frame(f) %>% head()
model.frame(f, data = dat) %>% head()  # only extracts data necessary (but does not do the interaction computations)

model.matrix(f, data = dat) %>% head()  # this does it!

model.frame(f_, data = dat) %>% head()

fit <- lm(f, data = dat)
summary(fit)

fit_ <- lm(f_, data = dat)
summary(fit_)

f3 <- formula(y ~ -1 + a + b + a:b)
model.matrix(f3) %>% head()

f4 <- formula(y ~ a + b + a:b + -1)
model.matrix(f4) %>% head()

plus100 <- function(x) x + 100

f5 <- formula(~ -1 + a)
model.matrix(f5) %>% head()

f6 <- formula(~ -1 + plus100(a))
model.matrix(f6) %>% head()
```
