---
title: "rmdcev-paper"
output: rmarkdown::pdf_document
vignette: >
  %\VignetteIndexEntry{rmdcev-paper}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Based on the paper, section **The rmdcev package**.

```{r setup}
library(rmdcev)
library(tidyverse)
```

```{r}
data(data_rec, package = "rmdcev")
aggregate(cbind(quant, price) ~ alt, data = data_rec, FUN = mean)

# prepare for estimation
data_mdcev <- mdcev.data(data_rec,
                         id.var = "id",
                         alt.var = "alt",
                         choice = "quant",
                         price = "price",
                         income = "income")

# all models are estimated via mdcev()
args(mdcev)
```

Intermezzo on the outside good

```{r}
# The difference is spent on the outside good (everything else than recreation)
data_rec %>%
  group_by(id, income) %>%
  summarise(sum_price = sum(price)) %>%
  ungroup()

test <- data_rec
test[1, "price"] <- test[1, "income"] + 1
test[1, "quant"] <- 1

try(
  mdcev.data(test,
             id.var = "id",
             alt.var = "alt",
             choice = "quant")
)
```

Estimating with the gamma profile

```{r}
data_model <- mdcev.data(data_rec, subset = id <= 200,
                         id.var = "id",
                         alt.var = "alt",
                         choice = "quant")

data_model$age_garden <- ifelse(data_model$alt == "garden",
                                data_model$ageindex, 0)  # alternatively in formula I(ageindex * (alt == "garden"))

# formula ~ 0 if only constants
mdcev_mle <- mdcev(~ age_garden,
                   data = data_model,
                   model = "gamma",
                   algorithm = "MLE",
                   print_iterations = FALSE)

class(mdcev_mle)
methods(class = class(mdcev_mle))  # no texreg

summary(mdcev_mle)
```

Latent class model

```{r}
data_model <- mdcev.data(data_rec, subset = id <= 1000,
                         id.var = "id",
                         alt.var = "alt",
                         choice = "quant")

mdcev_lc <- mdcev(~ 0 | university + ageindex + urban,
                  data = data_model,
                  n_classes = 2,
                  model = "gamma",
                  fixed_scale1 = 1,  # i.e. the error scale is the same for the two classes? If we don't do this we get singularity (identification) issues...
                  algorithm = "MLE",
                  print_iterations = FALSE)

summary(mdcev_lc)
```

